//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitCard
    {
        public int CardID { get; set; }
        public int AccountID { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Status { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
