//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanID { get; set; }
        public int CustomerID { get; set; }
        public int LoanTypeID { get; set; }
        public decimal Amount { get; set; }
        public int DurationMonths { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual LoanType LoanType { get; set; }
    }
}
