//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TransactionID { get; set; }
        public int AccountID { get; set; }
        public int TransactionTypeID { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
